export enum FilterNumberProperty {
  // Stock Schema
  PERATIO = 'pe',
  PRICE = 'price',
  MARKETCAP = 'marketCap',

  // Actual Values Schema
  CAPERATIO = 'actualValues.capeRatio',
  INTRINSICVALUEZEROGROWTH = 'actualValues.intrinsicValueZeroGrowth',
  INTRINSICVALUEAVERAGEGROWTH5Y = 'actualValues.intrinsicValueAverageGrowth5y',
  INTRINSICVALUELASTYEARGROWTH = 'actualValues.intrinsicValueLastYearGrowth',
  PETERLYNCHVALUE = 'actualValues.peterlynchValue',
  SHARESOUTSTANDING = 'actualValues.sharesOutstanding',
  SHARESOUTSTANDING5Y = 'actualValues.sharesOutstanding5y',
  ROE5Y = 'actualValues.roe5y',
  ROIC5Y = 'actualValues.roic5y',
  AVERAGEPROFITGROWTH5Y = 'actualValues.averageProfitGrowth5y',
  AVERAGEDIVIDENDGROWTH5Y = 'actualValues.averageDividendGrowth5y',
  AVERAGENETINCOMEGROWTH5Y = 'actualValues.averageNetIncomeGrowth5y',
  AVERAGEPROFITMARGIN5Y = 'actualValues.averageProfitMargin5y',
  DEBTPERSHARE = 'actualValues.debtPerShare',
  DIVIDENDYIELD5Y = 'actualValues.dividendYield5y',
  DIVIDENDPAYOUTRATIO5Y = 'actualValues.dividendPayoutRatio5y',
  BUYBACKYIELD = 'actualValues.buybackYield',
  SIMILARCOMPANIES = 'actualValues.similarCompanies',
  AVERAGEPESIMILARCOMPANIES = 'actualValues.averagePESimilarCompanies',
  AVERAGEPE5Y = 'actualValues.averagePE5y',
  FREECASHFLOW = 'actualValues.freeCashFlow',

  // Income Growth Metrics Schema
  GROWTHREVENUE = 'lastAnnualIncomeGrowthMetrics.growthRevenue',
  GROWTHCOSTOFREVENUE = 'lastAnnualIncomeGrowthMetrics.growthCostOfRevenue',
  GROWTHGROSSPROFIT = 'lastAnnualIncomeGrowthMetrics.growthGrossProfit',
  GROWTHGROSSPROFITRATIO = 'lastAnnualIncomeGrowthMetrics.growthGrossProfitRatio',
  GROWTHRESEARCHANDDEVELOPMENTEXPENSES = 'lastAnnualIncomeGrowthMetrics.growthResearchAndDevelopmentExpenses',
  GROWTHGENERALANDADMINISTRATIVEEXPENSES = 'lastAnnualIncomeGrowthMetrics.growthGeneralAndAdministrativeExpenses',
  GROWTHSELLINGANDMARKETINGEXPENSES = 'lastAnnualIncomeGrowthMetrics.growthSellingAndMarketingExpenses',
  GROWTHOTHEREXPENSES = 'lastAnnualIncomeGrowthMetrics.growthOtherExpenses',
  GROWTHOPERATINGEXPENSES = 'lastAnnualIncomeGrowthMetrics.growthOperatingExpenses',
  GROWTHCOSTANDEXPENSES = 'lastAnnualIncomeGrowthMetrics.growthCostAndExpenses',
  GROWTHINTERESTEXPENSE = 'lastAnnualIncomeGrowthMetrics.growthInterestExpense',
  GROWTHDEPRECIATIONANDAMORTIZATION = 'lastAnnualIncomeGrowthMetrics.growthDepreciationAndAmortization',
  GROWTHEBITDA = 'lastAnnualIncomeGrowthMetrics.growthEBITDA',
  GROWTHEBITDARATIO = 'lastAnnualIncomeGrowthMetrics.growthEBITDARatio',
  GROWTHOPERATINGINCOME = 'lastAnnualIncomeGrowthMetrics.growthOperatingIncome',
  GROWTHOPERATINGINCOMERATIO = 'lastAnnualIncomeGrowthMetrics.growthOperatingIncomeRatio',
  GROWTHTOTALOTHERINCOMEEXPENSESNET = 'lastAnnualIncomeGrowthMetrics.growthTotalOtherIncomeExpensesNet',
  GROWTHINCOMEBEFORETAX = 'lastAnnualIncomeGrowthMetrics.growthIncomeBeforeTax',
  GROWTHINCOMEBEFORETAXRATIO = 'lastAnnualIncomeGrowthMetrics.growthIncomeBeforeTaxRatio',
  GROWTHINCOMETAXEXPENSE = 'lastAnnualIncomeGrowthMetrics.growthIncomeTaxExpense',
  GROWTHNETINCOME = 'lastAnnualIncomeGrowthMetrics.growthNetIncome',
  GROWTHNETINCOMERATIO = 'lastAnnualIncomeGrowthMetrics.growthNetIncomeRatio',
  GROWTHEPS = 'lastAnnualIncomeGrowthMetrics.growthEPS',
  GROWTHEPSDILUTED = 'lastAnnualIncomeGrowthMetrics.growthEPSDiluted',
  GROWTHWEIGHTEDAVERAGESHSOUT = 'lastAnnualIncomeGrowthMetrics.growthWeightedAverageShsOut',
  GROWTHWEIGHTEDAVERAGESHSOUTDIL = 'lastAnnualIncomeGrowthMetrics.growthWeightedAverageShsOutDil',

  // Key Metrics Schema
  REVENUEPERSHARE = 'lastAnnualKeyMetrics.revenuePerShare',
  NETINCOMEPERSHARE = 'lastAnnualKeyMetrics.netIncomePerShare',
  OPERATINGCASHFLOWPERSHARE = 'lastAnnualKeyMetrics.operatingCashFlowPerShare',
  FREECASHFLOWPERSHARE = 'lastAnnualKeyMetrics.freeCashFlowPerShare',
  CASHPERSHARE = 'lastAnnualKeyMetrics.cashPerShare',
  BOOKVALUEPERSHARE = 'lastAnnualKeyMetrics.bookValuePerShare',
  TANGIBLEBOOKVALUEPERSHARE = 'lastAnnualKeyMetrics.tangibleBookValuePerShare',
  SHAREHOLDERSEQUITYPERSHARE = 'lastAnnualKeyMetrics.shareholdersEquityPerShare',
  INTERESTDEBTPERSHARE = 'lastAnnualKeyMetrics.interestDebtPerShare',
  ENTERPRISEVALUE = 'lastAnnualKeyMetrics.enterpriseValue',
  PRICETOBOOKRATIO = 'lastAnnualKeyMetrics.priceToBookRatio',
  PRICETOSALESRATIO = 'lastAnnualKeyMetrics.priceToSalesRatio',
  POCRRATIO = 'lastAnnualKeyMetrics.pocfRatio',
  PFCFRATIO = 'lastAnnualKeyMetrics.pfcfRatio',
  PBRATIO = 'lastAnnualKeyMetrics.pbRatio',
  PTBRATIO = 'lastAnnualKeyMetrics.ptbRatio',
  EVTOSALES = 'lastAnnualKeyMetrics.evToSales',
  EVTOEBITDA = 'lastAnnualKeyMetrics.evToEBITDA',
  EVTOOPERATINGCASHFLOW = 'lastAnnualKeyMetrics.evToOperatingCashFlow',
  EVTOFREECASHFLOW = 'lastAnnualKeyMetrics.evToFreeCashFlow',
  EARNINGSYIELD = 'lastAnnualKeyMetrics.earningsYield',
  FREECASHFLOWYIELD = 'lastAnnualKeyMetrics.freeCashFlowYield',
  DEBTTOEQUITY = 'lastAnnualKeyMetrics.debtToEquity',
  DEBTTOASSETS = 'lastAnnualKeyMetrics.debtToAssets',
  NETDEBTOEBITDA = 'lastAnnualKeyMetrics.netDebtToEBITDA',
  CURRENTRATIO = 'lastAnnualKeyMetrics.currentRatio',
  INTERESTCOVERAGE = 'lastAnnualKeyMetrics.interestCoverage',
  INCOMEQUALITY = 'lastAnnualKeyMetrics.incomeQuality',
  DIVIDENDYIELD = 'lastAnnualKeyMetrics.dividendYield',
  PAYOUTRATIO = 'lastAnnualKeyMetrics.payoutRatio',
  SGAREVENUE = 'lastAnnualKeyMetrics.sgaRevenue',
  RDREVENUE = 'lastAnnualKeyMetrics.rdRevenue',
  INTANGIBLESTOTALASSETS = 'lastAnnualKeyMetrics.intangiblesTotalAssets',
  CAPEXTOPPERATINGCASHFLOW = 'lastAnnualKeyMetrics.capexToOperatingCashFlow',
  CAPEXTOTOTALREVENUE = 'lastAnnualKeyMetrics.capexToTotalRevenue',
  CAPEXTOEBITDA = 'lastAnnualKeyMetrics.capexToEBITDA',
  STOCKBASEDCOMPENSATIONTOREVENUE = 'lastAnnualKeyMetrics.stockBasedCompensationToRevenue',
  GRAHAMNUMBER = 'lastAnnualKeyMetrics.grahamNumber',
  ROIC = 'lastAnnualKeyMetrics.roic',
  RETURNONTANGIBLEASSETS = 'lastAnnualKeyMetrics.returnOnTangibleAssets',
  GRAHAMNETNET = 'lastAnnualKeyMetrics.grahamNetNet',
  WORKINGCAPITAL = 'lastAnnualKeyMetrics.workingCapital',
  TANGIBLEASSETVALUE = 'lastAnnualKeyMetrics.tangibleAssetValue',
  NETCURRENTASSETVALUE = 'lastAnnualKeyMetrics.netCurrentAssetValue',
  INVESTEDCAPITAL = 'lastAnnualKeyMetrics.investedCapital',
  AVERAGERECEIVABLES = 'lastAnnualKeyMetrics.averageReceivables',
  AVERAGEPAYABLES = 'lastAnnualKeyMetrics.averagePayables',
  AVERAGEINVENTORY = 'lastAnnualKeyMetrics.averageInventory',
  DAYSSALESOUTSTANDING = 'lastAnnualKeyMetrics.daysSalesOutstanding',
  DAYSPAYABLESOUTSTANDING = 'lastAnnualKeyMetrics.daysPayablesOutstanding',
  DAYSOFINVENTORYONHAND = 'lastAnnualKeyMetrics.daysOfInventoryOnHand',
  RECEIVABLESTURNOVER = 'lastAnnualKeyMetrics.receivablesTurnover',
  PAYABLESTURNOVER = 'lastAnnualKeyMetrics.payablesTurnover',
  INVENTORYTURNOVER = 'lastAnnualKeyMetrics.inventoryTurnover',
  ROE = 'lastAnnualKeyMetrics.roe',
  CAPEXPERSHARE = 'lastAnnualKeyMetrics.capexPerShare',

  // Profit Growth Metrics Schema
  GROWTHDEFERREDINCOMETAX = 'lastAnnualProfitGrowthMetrics.growthDeferredIncomeTax',
  GROWTHSTOCKBASEDCOMPENSATION = 'lastAnnualProfitGrowthMetrics.growthStockBasedCompensation',
  GROWTHCHANGEINWORKINGCAPITAL = 'lastAnnualProfitGrowthMetrics.growthChangeInWorkingCapital',
  GROWTHACCOUNTSRECEIVABLES = 'lastAnnualProfitGrowthMetrics.growthAccountsReceivables',
  GROWTHINVENTORY = 'lastAnnualProfitGrowthMetrics.growthInventory',
  GROWTHACCOUNTSPAYABLES = 'lastAnnualProfitGrowthMetrics.growthAccountsPayables',
  GROWTHOTHERWORKINGCAPITAL = 'lastAnnualProfitGrowthMetrics.growthOtherWorkingCapital',
  GROWTHOTHERNONCASHITEMS = 'lastAnnualProfitGrowthMetrics.growthOtherNonCashItems',
  GROWTHNETCASHPROVIDEDBYOPERATINGACTIVITIES = 'lastAnnualProfitGrowthMetrics.growthNetCashProvidedByOperatingActivities',
  GROWTHINVESTMENTSINPROPERTYPLANTANDEQUIPMENT = 'lastAnnualProfitGrowthMetrics.growthInvestmentsInPropertyPlantAndEquipment',
  GROWTHACQUISITIONSNET = 'lastAnnualProfitGrowthMetrics.growthAcquisitionsNet',
  GROWTHPURCHASESOFINVESTMENTS = 'lastAnnualProfitGrowthMetrics.growthPurchasesOfInvestments',
  GROWTHSALESMATURITIESOFINVESTMENTS = 'lastAnnualProfitGrowthMetrics.growthSalesMaturitiesOfInvestments',
  GROWTHOTHERINVESTINGACTIVITIES = 'lastAnnualProfitGrowthMetrics.growthOtherInvestingActivities',
  GROWTHNETCASHUSEDFORINVESTINGACTIVITIES = 'lastAnnualProfitGrowthMetrics.growthNetCashUsedForInvestingActivities',
  GROWTHDEBTREPAYMENT = 'lastAnnualProfitGrowthMetrics.growthDebtRepayment',
  GROWTHCOMMONSTOCKISSUED = 'lastAnnualProfitGrowthMetrics.growthCommonStockIssued',
  GROWTHCOMMONSTOCKREPURCHASED = 'lastAnnualProfitGrowthMetrics.growthCommonStockRepurchased',
  GROWTHDIVIDENDS = 'lastAnnualProfitGrowthMetrics.growthDividends',
  GROWTHOTHERFINANCINGACTIVITIES = 'lastAnnualProfitGrowthMetrics.growthOtherFinancingActivities',
  GROWTHNETCASHUSEDPROVIDEDBYFINANCINGACTIVITIES = 'lastAnnualProfitGrowthMetrics.growthNetCashUsedProvidedByFinancingActivities',
  GROWTHEFFECTOFFOREXCHANGESONCASH = 'lastAnnualProfitGrowthMetrics.growthEffectOfForexChangesOnCash',
  GROWTHNETCHANGEINCASH = 'lastAnnualProfitGrowthMetrics.growthNetChangeInCash',
  GROWTHCASHATENDOFYEAR = 'lastAnnualProfitGrowthMetrics.growthCashAtEndOfYear',
  GROWTHCASHATBEGINNINGOFYEAR = 'lastAnnualProfitGrowthMetrics.growthCashAtBeginningOfYear',
  GROWTHOPERATINGCASHFLOW = 'lastAnnualProfitGrowthMetrics.growthOperatingCashFlow',
  GROWTHCAPITALEXPENDITURE = 'lastAnnualProfitGrowthMetrics.growthCapitalExpenditure',
  GROWTHFREECASHFLOW = 'lastAnnualProfitGrowthMetrics.growthFreeCashFlow',

  // Balance Sheet Statement Schema
  TOTALASSETS = 'lastAnnualBalanceSheetStatement.totalAssets',
  TOTALLIABILITIES = 'lastAnnualBalanceSheetStatement.totalLiabilities',
  TOTALSHAREHOLDEREQUITY = 'lastAnnualBalanceSheetStatement.totalShareholderEquity',
  CASHANDCASHEQUIVALENTS = 'lastAnnualBalanceSheetStatement.cashAndCashEquivalents',
  SHORTTERMINVESTMENTS = 'lastAnnualBalanceSheetStatement.shortTermInvestments',
  RECEIVABLES = 'lastAnnualBalanceSheetStatement.receivables',
  // INVENTORY = 'lastAnnualBalanceSheetStatement.inventory',
  OTHERCURRENTASSETS = 'lastAnnualBalanceSheetStatement.otherCurrentAssets',
  TOTALCURRENTASSETS = 'lastAnnualBalanceSheetStatement.totalCurrentAssets',
  PROPERTYPLANTANDEQUIPMENT = 'lastAnnualBalanceSheetStatement.propertyPlantAndEquipment',
  GOODWILL = 'lastAnnualBalanceSheetStatement.goodwill',
  INTANGIBLEASSETS = 'lastAnnualBalanceSheetStatement.intangibleAssets',
  LONGTERMINVESTMENTS = 'lastAnnualBalanceSheetStatement.longTermInvestments',
  OTHERASSETS = 'lastAnnualBalanceSheetStatement.otherAssets',
  TOTALNONCURRENTASSETS = 'lastAnnualBalanceSheetStatement.totalNonCurrentAssets',
  // TOTALASSETS = 'lastAnnualBalanceSheetStatement.totalAssets',
  // ACCOUNTS_PAYABLE = 'lastAnnualBalanceSheetStatement.accountsPayable',
  SHORTTERMDEBT = 'lastAnnualBalanceSheetStatement.shortTermDebt',
  OTHERCURRENTLIABILITIES = 'lastAnnualBalanceSheetStatement.otherCurrentLiabilities',
  TOTALCURRENTLIABILITIES = 'lastAnnualBalanceSheetStatement.totalCurrentLiabilities',
  LONGTERMDEBT = 'lastAnnualBalanceSheetStatement.longTermDebt',
  OTHERNONCURRENTLIABILITIES = 'lastAnnualBalanceSheetStatement.otherNonCurrentLiabilities',
  TOTALNONCURRENTLIABILITIES = 'lastAnnualBalanceSheetStatement.totalNonCurrentLiabilities',
  // TOTALLIABILITIES = 'lastAnnualBalanceSheetStatement.totalLiabilities',
  // TOTALSHAREHOLDEREQUITY = 'lastAnnualBalanceSheetStatement.totalShareholderEquity',

  // Cash Flow Statement Schema
  NETINCOME = 'lastAnnualCashFlowStatement.netIncome',
  DEPRECIATIONANDAMORTIZATION = 'lastAnnualCashFlowStatement.depreciationAndAmortization',
  DEFERREDINCOME_TAX = 'lastAnnualCashFlowStatement.deferredIncomeTax',
  STOCKBASED_COMPENSATION = 'lastAnnualCashFlowStatement.stockBasedCompensation',
  CHANGEINWORKING_CAPITAL = 'lastAnnualCashFlowStatement.changeInWorkingCapital',
  ACCOUNTSRECEIVABLE = 'lastAnnualCashFlowStatement.accountsReceivable',
  INVENTORY = 'lastAnnualCashFlowStatement.inventory',
  ACCOUNTS_PAYABLE = 'lastAnnualCashFlowStatement.accountsPayable',
  OTHERWORKING_CAPITAL = 'lastAnnualCashFlowStatement.otherWorkingCapital',
  OTHER_NONCASH_ITEMS = 'lastAnnualCashFlowStatement.otherNonCashItems',
  NET_CASH_PROVIDED_BY_OPERATING_ACTIVITIES = 'lastAnnualCashFlowStatement.netCashProvidedByOperatingActivities',
  INVESTMENTS_IN_PROPERTY_PLANT_AND_EQUIPMENT = 'lastAnnualCashFlowStatement.investmentsInPropertyPlantAndEquipment',
  ACQUISITIONS_NET = 'lastAnnualCashFlowStatement.acquisitionsNet',
  PURCHASES_OF_INVESTMENTS = 'lastAnnualCashFlowStatement.purchasesOfInvestments',
  SALES_MATURITIES_OF_INVESTMENTS = 'lastAnnualCashFlowStatement.salesMaturitiesOfInvestments',
  OTHERINVESTING_ACTIVITIES = 'lastAnnualCashFlowStatement.otherInvestingActivities',
  NET_CASH_USED_FOR_INVESTING_ACTIVITIES = 'lastAnnualCashFlowStatement.netCashUsedForInvestingActivities',
  DEBT_REPAYMENT = 'lastAnnualCashFlowStatement.debtRepayment',
  COMMON_STOCK_ISSUED = 'lastAnnualCashFlowStatement.commonStockIssued',
  COMMON_STOCK_REPURCHASED = 'lastAnnualCashFlowStatement.commonStockRepurchased',
  DIVIDENDS_PAID = 'lastAnnualCashFlowStatement.dividendsPaid',
  OTHER_FINANCING_ACTIVITIES = 'lastAnnualCashFlowStatement.otherFinancingActivities',
  NET_CASH_PROVIDED_BY_FINANCING_ACTIVITIES = 'lastAnnualCashFlowStatement.netCashProvidedByFinancingActivities',
  EFFECT_OF_FOREX_CHANGES_ON_CASH = 'lastAnnualCashFlowStatement.effectOfForexChangesOnCash',
  NET_CHANGE_IN_CASH = 'lastAnnualCashFlowStatement.netChangeInCash',
  CASH_AT_END_OF_YEAR = 'lastAnnualCashFlowStatement.cashAtEndOfYear',
  CASH_AT_BEGINNING_OF_YEAR = 'lastAnnualCashFlowStatement.cashAtBeginningOfYear',
}

export enum MultiCriteriaType {
  COUNTRY = 'country',
  SECTOR = 'sector',
  INDUSTRY = 'industry',
}

export enum FilterStringProperty {
  SYMBOL = 'symbol',
  NAME = 'name',
  EXCHANGE = 'exchange',
}

export enum FilterNumberCondition {
  GREATER_THAN = 'greater_than',
  LESS_THAN = 'less_than',
}

export enum FilterStringCondition {
  EQUAL = 'equal',
  NOT_EQUAL = 'not_equal',
}
