export enum FilterNumberProperty {
  PERATIO = 'peRatio',
  PRICE = 'price',
  MARKETCAP = 'marketCap',

  // Actual Values Schema
  CAPERATIO = 'capeRatio',
  INTRINSICVALUEZEROGROWTH = 'intrinsicValueZeroGrowth',
  INTRINSICVALUEAVERAGEGROWTH5Y = 'intrinsicValueAverageGrowth5y',
  INTRINSICVALUELASTYEARGROWTH = 'intrinsicValueLastYearGrowth',
  PETERLYNCHVALUE = 'peterlynchValue',
  SHARESOUTSTANDING = 'sharesOutstanding',
  SHARESOUTSTANDING5Y = 'sharesOutstanding5y',
  ROE5Y = 'roe5y',
  ROIC5Y = 'roic5y',
  AVERAGEPROFITGROWTH5Y = 'averageProfitGrowth5y',
  AVERAGEDIVIDENDGROWTH5Y = 'averageDividendGrowth5y',
  AVERAGENETINCOMEGROWTH5Y = 'averageNetIncomeGrowth5y',
  AVERAGEPROFITMARGIN5Y = 'averageProfitMargin5y',
  DEBTPERSHARE = 'debtPerShare',
  DIVIDENDYIELD5Y = 'dividendYield5y',
  DIVIDENDPAYOUTRATIO5Y = 'dividendPayoutRatio5y',
  BUYBACKYIELD = 'buybackYield',
  SIMILARCOMPANIES = 'similarCompanies',
  AVERAGEPESIMILARCOMPANIES = 'averagePESimilarCompanies',
  AVERAGEPE5Y = 'averagePE5y',
  FREECASHFLOW = 'freeCashFlow',

  // Income Growth Metrics Schema
  GROWTHREVENUE = 'growthRevenue',
  GROWTHCOSTOFREVENUE = 'growthCostOfRevenue',
  GROWTHGROSSPROFIT = 'growthGrossProfit',
  GROWTHGROSSPROFITRATIO = 'growthGrossProfitRatio',
  GROWTHRESEARCHANDDEVELOPMENTEXPENSES = 'growthResearchAndDevelopmentExpenses',
  GROWTHGENERALANDADMINISTRATIVEEXPENSES = 'growthGeneralAndAdministrativeExpenses',
  GROWTHSELLINGANDMARKETINGEXPENSES = 'growthSellingAndMarketingExpenses',
  GROWTHOTHEREXPENSES = 'growthOtherExpenses',
  GROWTHOPERATINGEXPENSES = 'growthOperatingExpenses',
  GROWTHCOSTANDEXPENSES = 'growthCostAndExpenses',
  GROWTHINTERESTEXPENSE = 'growthInterestExpense',
  GROWTHDEPRECIATIONANDAMORTIZATION = 'growthDepreciationAndAmortization',
  GROWTHEBITDA = 'growthEBITDA',
  GROWTHEBITDARATIO = 'growthEBITDARatio',
  GROWTHOPERATINGINCOME = 'growthOperatingIncome',
  GROWTHOPERATINGINCOMERATIO = 'growthOperatingIncomeRatio',
  GROWTHTOTALOTHERINCOMEEXPENSESNET = 'growthTotalOtherIncomeExpensesNet',
  GROWTHINCOMEBEFORETAX = 'growthIncomeBeforeTax',
  GROWTHINCOMEBEFORETAXRATIO = 'growthIncomeBeforeTaxRatio',
  GROWTHINCOMETAXEXPENSE = 'growthIncomeTaxExpense',
  GROWTHNETINCOME = 'growthNetIncome',
  GROWTHNETINCOMERATIO = 'growthNetIncomeRatio',
  GROWTHEPS = 'growthEPS',
  GROWTHEPSDILUTED = 'growthEPSDiluted',
  GROWTHWEIGHTEDAVERAGESHSOUT = 'growthWeightedAverageShsOut',
  GROWTHWEIGHTEDAVERAGESHSOUTDIL = 'growthWeightedAverageShsOutDil',

  // Key Metrics Schema
  REVENUEPERSHARE = 'revenuePerShare',
  NETINCOMEPERSHARE = 'netIncomePerShare',
  OPERATINGCASHFLOWPERSHARE = 'operatingCashFlowPerShare',
  FREECASHFLOWPERSHARE = 'freeCashFlowPerShare',
  CASHPERSHARE = 'cashPerShare',
  BOOKVALUEPERSHARE = 'bookValuePerShare',
  TANGIBLEBOOKVALUEPERSHARE = 'tangibleBookValuePerShare',
  SHAREHOLDERSEQUITYPERSHARE = 'shareholdersEquityPerShare',
  INTERESTDEBTPERSHARE = 'interestDebtPerShare',
  ENTERPRISEVALUE = 'enterpriseValue',
  PRICETOBOOKRATIO = 'priceToBookRatio',
  PRICETOSALESRATIO = 'priceToSalesRatio',
  POCRRATIO = 'pocfRatio',
  PFCFRATIO = 'pfcfRatio',
  PBRATIO = 'pbRatio',
  PTBRATIO = 'ptbRatio',
  EVTOSALES = 'evToSales',
  EVTOEBITDA = 'evToEBITDA',
  EVTOOPERATINGCASHFLOW = 'evToOperatingCashFlow',
  EVTOFREECASHFLOW = 'evToFreeCashFlow',
  EARNINGSYIELD = 'earningsYield',
  FREECASHFLOWYIELD = 'freeCashFlowYield',
  DEBTTOEQUITY = 'debtToEquity',
  DEBTTOASSETS = 'debtToAssets',
  NETDEBTOEBITDA = 'netDebtToEBITDA',
  CURRENTRATIO = 'currentRatio',
  INTERESTCOVERAGE = 'interestCoverage',
  INCOMEQUALITY = 'incomeQuality',
  DIVIDENDYIELD = 'dividendYield',
  PAYOUTRATIO = 'payoutRatio',
  SGAREVENUE = 'sgaRevenue',
  RDREVENUE = 'rdRevenue',
  INTANGIBLESTOTALASSETS = 'intangiblesTotalAssets',
  CAPEXTOPPERATINGCASHFLOW = 'capexToOperatingCashFlow',
  CAPEXTOTOTALREVENUE = 'capexToTotalRevenue',
  CAPEXTOEBITDA = 'capexToEBITDA',
  STOCKBASEDCOMPENSATIONTOREVENUE = 'stockBasedCompensationToRevenue',
  GRAHAMNUMBER = 'grahamNumber',
  ROIC = 'roic',
  RETURNONTANGIBLEASSETS = 'returnOnTangibleAssets',
  GRAHAMNETNET = 'grahamNetNet',
  WORKINGCAPITAL = 'workingCapital',
  TANGIBLEASSETVALUE = 'tangibleAssetValue',
  NETCURRENTASSETVALUE = 'netCurrentAssetValue',
  INVESTEDCAPITAL = 'investedCapital',
  AVERAGERECEIVABLES = 'averageReceivables',
  AVERAGEPAYABLES = 'averagePayables',
  AVERAGEINVENTORY = 'averageInventory',
  DAYSSALESOUTSTANDING = 'daysSalesOutstanding',
  DAYSPAYABLESOUTSTANDING = 'daysPayablesOutstanding',
  DAYSOFINVENTORYONHAND = 'daysOfInventoryOnHand',
  RECEIVABLESTURNOVER = 'receivablesTurnover',
  PAYABLESTURNOVER = 'payablesTurnover',
  INVENTORYTURNOVER = 'inventoryTurnover',
  ROE = 'roe',
  CAPEXPERSHARE = 'capexPerShare',

  // Profit Growth Metrics Schema
  GROWTHDEFERREDINCOMETAX = 'growthDeferredIncomeTax',
  GROWTHSTOCKBASEDCOMPENSATION = 'growthStockBasedCompensation',
  GROWTHCHANGEINWORKINGCAPITAL = 'growthChangeInWorkingCapital',
  GROWTHACCOUNTSRECEIVABLES = 'growthAccountsReceivables',
  GROWTHINVENTORY = 'growthInventory',
  GROWTHACCOUNTSPAYABLES = 'growthAccountsPayables',
  GROWTHOTHERWORKINGCAPITAL = 'growthOtherWorkingCapital',
  GROWTHOTHERNONCASHITEMS = 'growthOtherNonCashItems',
  GROWTHNETCASHPROVIDEDBYOPERATINGACTIVITIES = 'growthNetCashProvidedByOperatingActivities',
  GROWTHINVESTMENTSINPROPERTYPLANTANDEQUIPMENT = 'growthInvestmentsInPropertyPlantAndEquipment',
  GROWTHACQUISITIONSNET = 'growthAcquisitionsNet',
  GROWTHPURCHASESOFINVESTMENTS = 'growthPurchasesOfInvestments',
  GROWTHSALESMATURITIESOFINVESTMENTS = 'growthSalesMaturitiesOfInvestments',
  GROWTHOTHERINVESTINGACTIVITIES = 'growthOtherInvestingActivities',
  GROWTHNETCASHUSEDFORINVESTINGACTIVITIES = 'growthNetCashUsedForInvestingActivities',
  GROWTHDEBTREPAYMENT = 'growthDebtRepayment',
  GROWTHCOMMONSTOCKISSUED = 'growthCommonStockIssued',
  GROWTHCOMMONSTOCKREPURCHASED = 'growthCommonStockRepurchased',
  GROWTHDIVIDENDS = 'growthDividends',
  GROWTHOTHERFINANCINGACTIVITIES = 'growthOtherFinancingActivities',
  GROWTHNETCASHUSEDPROVIDEDBYFINANCINGACTIVITIES = 'growthNetCashUsedProvidedByFinancingActivities',
  GROWTHEFFECTOFFOREXCHANGESONCASH = 'growthEffectOfForexChangesOnCash',
  GROWTHNETCHANGEINCASH = 'growthNetChangeInCash',
  GROWTHCASHATENDOFYEAR = 'growthCashAtEndOfYear',
  GROWTHCASHATBEGINNINGOFYEAR = 'growthCashAtBeginningOfYear',
  GROWTHOPERATINGCASHFLOW = 'growthOperatingCashFlow',
  GROWTHCAPITALEXPENDITURE = 'growthCapitalExpenditure',
  GROWTHFREECASHFLOW = 'growthFreeCashFlow',
}

export enum FilterStringProperty {
  SYMBOL = 'symbol',
  NAME = 'name',
  EXCHANGE = 'exchange',
}

export enum FilterCondition {
  GREATER_THAN = 'greater_than',
  LESS_THAN = 'less_than',
  EQUAL = 'equal',
  NOT_EQUAL = 'not_equal',
}
