### List all stocks
GET http://localhost:3000/stocks

### Get stock by id
GET http://localhost:3000/stocks/AAPL

### Create a new user
POST http://localhost:3000/users
content-type: application/json

{
    "email": 123,
    "password": ""
}

### Update stock list by EXCHANGE
POST http://localhost:3000/stocks/update
content-type: application/json

{
    "stockExchange": "NASDAQ"
}

### Update statement of stock
POST http://localhost:3000/statements/AAPL/update-statements
content-type: application/json

### Update metrics of stock
POST http://localhost:3000/fmp/AAPL/update-metrics
content-type: application/json

### Update analyst rating of stock
POST http://localhost:3000/fmp/AAPL/update-analyst-ratings


### Get combined data for a stock symbol and period type
GET http://localhost:3000/statements/AAPL/combine?periodType=quarter&properties=inventory&properties=totalInvestments&properties=operatingExpenses

### Post to update outlook for a stock
POST  http://localhost:3000/fmp/AAPL/update-outlook

### Post to update  update-analyst-ratings
POST  http://localhost:3000/fmp/AAPL/update-analyst-ratings