export interface Values {
    exchange?: string
    peRatio?: number
    capeRatio?: number
    marketCap?: number
    date?: string
    dcf?: number
    price?: number
    intrinsicValueZeroGrowth?: number
    intrinsicValueAverageGrowth?: number
    intrinsicValueLastYearGrowth?: number
    peterlynchValue?: number
    sharesOutstanding?: number
    sharesOutstanding5y?: number
    roe10y?: number
    roe?: number
    roic?: number
    roic10y?: number
    averageProfitGrowth?: number
    averageDividendGrowth?: number
    averageNetIncomeGrowth?: number
    averageProfitMargin?: number
    profitMargin?: number
    eps?: number
    debtPerShare?: number
    dividendYield?: number
    dividendYield10y?: number
    dividendPayoutRatio?: number
    freeCashFlowPerShare?: number
    buybackYield?: number
    buybackPayoutRatio?: number
    debtToEquity?: number
    debtToAssets?: number
    netDebtToEBITDA?: number
    similarCompanies?: string[]
    averagePESimilarCompanies?: number
    yearReturn?: number
}
