apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
        - name: be
          image: mrodl/stocks-be
          resources:
            limits:
              memory: 516Mi
              cpu: "0.4"
            requests:
              memory: 128Mi
              cpu: "0.1"
          env:
            - name: MONGO_URI
              value: "mongodb://be-mongo-srv:27017/stocks"
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 240
            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: be-srv
spec:
  type: NodePort
  selector:
    app: be
  ports:
    - name: be
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31515
