apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: be-mongo
    name: be-mongo-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: be-mongo
    strategy: {}
    template:
        metadata:
            labels:
                app: be-mongo
        spec:
            containers:
                - image: mongo
                  name: be-mongo
                  resources:
                      limits:
                          memory: 256Mi
                          cpu: '0.2'
                      requests:
                          memory: 128Mi
                          cpu: '0.1'
                  args: ['--dbpath', '/data/stocksdb']
                  volumeMounts:
                      - name: 'mongo-data-dir'
                        mountPath: '/data/stocksdb'
            volumes:
                - name: 'mongo-data-dir'
                  persistentVolumeClaim:
                      claimName: 'stocks-data'
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: be-mongo
    name: be-mongo-srv
spec:
    ports:
        - port: 27017
          protocol: TCP
          targetPort: 27017
          nodePort: 32001
    selector:
        app: be-mongo
    type: NodePort
status:
    loadBalancer: {}
