apiVersion: apps/v1
kind: Deployment
metadata:
    name: stocks-be-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: stocks-be
    template:
        metadata:
            labels:
                app: stocks-be
        spec:
            containers:
                - name: be
                  image: mrodl/stocks-be:1.0.28
                  imagePullPolicy: Always
                  resources:
                      limits:
                          memory: 2048Mi
                          cpu: '0.8'
                      requests:
                          memory: 256Mi
                          cpu: '0.2'
                  env:
                      - name: MONGO_URI
                        value: 'mongodb://stocks-mongo-srv:27017/stocks'
                      - name: API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: fmp-secret
                                key: FMP_KEY
                  livenessProbe:
                      httpGet:
                          path: /be-stocks/api/status
                          port: 3000
                      initialDelaySeconds: 240
                      periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
    name: stocks-be-srv
spec:
    type: NodePort
    selector:
        app: stocks-be
    ports:
        - name: stocks-be
          protocol: TCP
          port: 3000
          targetPort: 3000
          nodePort: 31515
