apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: stocks-be-application
    namespace: argocd
    annotations:
        argocd-image-updater.argoproj.io/image-list: 'be=mrodl/stocks-be'
        argocd-image-updater.argoproj.io/be.tag-match: 'regexp:^[0-9]+\.[0-9]+\.[0-9]+$'
        argocd-image-updater.argoproj.io/be.force-update: 'true'
spec:
    project: default
    source:
        repoURL: https://github.com/martinrodl/stock-screener.git/
        path: infra/k8s
        targetRevision: prod
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
