import mongoose from "mongoose";

const keyMetricsSchema = new mongoose.Schema(
  {
    date: String,
    calendarYear: String,
    period: String,
    revenuePerShare: Number,
    netIncomePerShare: Number,
    operatingCashFlowPerShare: Number,
    freeCashFlowPerShare: Number,
    cashPerShare: Number,
    bookValuePerShare: Number,
    tangibleBookValuePerShare: Number,
    shareholdersEquityPerShare: Number,
    interestDebtPerShare: Number,
    marketCap: Number,
    enterpriseValue: Number,
    peRatio: Number,
    priceToSalesRatio: Number,
    pocfratio: Number,
    pfcfRatio: Number,
    pbRatio: Number,
    ptbRatio: Number,
    evToSales: Number,
    enterpriseValueOverEBITDA: Number,
    evToOperatingCashFlow: Number,
    evToFreeCashFlow: Number,
    earningsYield: Number,
    freeCashFlowYield: Number,
    debtToEquity: Number,
    debtToAssets: Number,
    netDebtToEBITDA: Number,
    currentRatio: Number,
    interestCoverage: Number,
    incomeQuality: Number,
    dividendYield: Number,
    payoutRatio: Number,
    salesGeneralAndAdministrativeToRevenue: Number,
    researchAndDdevelopementToRevenue: Number,
    intangiblesToTotalAssets: Number,
    capexToOperatingCashFlow: Number,
    capexToRevenue: Number,
    capexToDepreciation: Number,
    stockBasedCompensationToRevenue: Number,
    grahamNumber: Number,
    roic: Number,
    returnOnTangibleAssets: Number,
    grahamNetNet: Number,
    workingCapital: Number,
    tangibleAssetValue: Number,
    netCurrentAssetValue: Number,
    investedCapital: Number,
    averageReceivables: Number,
    averagePayables: Number,
    averageInventory: Number,
    daysSalesOutstanding: Number,
    daysPayablesOutstanding: Number,
    daysOfInventoryOnHand: Number,
    receivablesTurnover: Number,
    payablesTurnover: Number,
    inventoryTurnover: Number,
    roe: Number,
    capexPerShare: Number,
  },
  { timestamps: true }
);

// keyMetricsSchema.index({ symbol: 1, date: 1 }, { unique: true });

const KeyMetrics = mongoose.model("KeyMetrics", keyMetricsSchema);

export default KeyMetrics;
