# .github/workflows/update-version.yml


name: Update Version

on:
  push:
    branches:
      - prod

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Increment Backend Version
        run: |
          cd be
          npm version patch -m "Increment backend version [skip ci]"
          git push

      - name: Increment Frontend Version
        run: |
          cd frontend
          npm version patch -m "Increment frontend version [skip ci]"
          git push

      - name: Build and Push Docker Image
        run: |
          cd be
          docker build -t mrodl/stock-be:latest .
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push mrodl/stock-be:latest

